server:
  port: 8999
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        exclude: "*"
  health:
    redis:
      enabled: false

spring:
  #profiles:
  #include: common-dev

  main:
    allow-bean-definition-overriding: true

  aop:
    proxy-target-class: true

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 50MB

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/sync_data?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&rewriteBatchedStatements=true
          username: root
          password: root
          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
          initial-size: 3
          min-idle: 5
          max-active: 20
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 1 FROM DUAL
          test-while-idle: false
          test-on-borrow: false
          test-on-return: false

#redis
redisson:
  host: localhost
  port: 6379
  minimumIdleSize: 5
  connectionPoolSize: 5
#  username: aaa
#  password: aaa

#开启驼峰命名
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true
